package codex

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pelletier/go-toml/v2"

	"github.com/cairon666/agentsflow/internal/adapter"
	"github.com/cairon666/agentsflow/internal/binding"
	"github.com/cairon666/agentsflow/internal/install"
	"github.com/cairon666/agentsflow/internal/ir"
)

func TestRenderCreatesCodexAgent(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt-test"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	want := filepath.Join(workDir, ".codex", "agents", "reviewer.toml")
	found := false
	for _, action := range plan.Actions {
		if action.Path == want {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected action for %s, got %#v", want, plan.Actions)
	}

	config := actionContent(t, plan, filepath.Join(workDir, ".codex", "config.toml"))
	for _, want := range []string{
		"[features]",
		"multi_agent = true",
		"[agents]",
		"max_threads = 7",
		"max_depth = 2",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("expected config.toml to contain %q, got:\n%s", want, config)
		}
	}
}

func TestRenderOmitsGeneratedMarker(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt-test"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	for _, action := range plan.Actions {
		if strings.Contains(string(action.Content), "Generated by agentsflow") {
			t.Fatalf("action %s contains generated marker:\n%s", action.Path, action.Content)
		}
	}
}

func TestRenderCodexAgentUsesMultilineDeveloperInstructions(t *testing.T) {
	workDir := t.TempDir()
	flow := testFlow()
	agent := flow.Agents["reviewer"]
	agent.Prompt = "Line one.\n\n- Line two\n- Line three\n"
	flow.Agents["reviewer"] = agent
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    flow,
		Models:  binding.Models{"main": "gpt-test"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	content := actionContent(t, plan, filepath.Join(workDir, ".codex", "agents", "reviewer.toml"))
	if !strings.Contains(content, "developer_instructions = \"\"\"\nLine one.\n\n- Line two\n- Line three\n\"\"\"") {
		t.Fatalf("developer_instructions was not rendered as multiline TOML:\n%s", content)
	}
	var parsed map[string]any
	if err := toml.Unmarshal([]byte(content), &parsed); err != nil {
		t.Fatal(err)
	}
	if parsed["developer_instructions"] != agent.Prompt {
		t.Fatalf("developer_instructions = %#v, want %#v", parsed["developer_instructions"], agent.Prompt)
	}
}

func TestRenderCodexAgentMapsWebSearchCapability(t *testing.T) {
	workDir := t.TempDir()
	flow := testFlow()
	flow.PermissionProfiles["docs"] = ir.PermissionProfile{
		Capabilities: map[string]string{
			"edit_files": "deny",
			"web_search": "allow",
		},
	}
	flow.Agents["docs-researcher"] = ir.Agent{
		ID:                "docs-researcher",
		Description:       "Researches docs",
		ModelSlot:         "main",
		ReasoningEffort:   "medium",
		PermissionProfile: "docs",
		Prompt:            "Research.",
	}

	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    flow,
		Models:  binding.Models{"main": "gpt-test"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	docs := actionContent(t, plan, filepath.Join(workDir, ".codex", "agents", "docs-researcher.toml"))
	if !strings.Contains(docs, "web_search = 'live'") {
		t.Fatalf("expected docs-researcher to enable live web_search, got:\n%s", docs)
	}

	reviewer := actionContent(t, plan, filepath.Join(workDir, ".codex", "agents", "reviewer.toml"))
	if !strings.Contains(reviewer, "web_search = 'disabled'") {
		t.Fatalf("expected reviewer to disable web_search, got:\n%s", reviewer)
	}
}

func TestRenderMergesConfigTOML(t *testing.T) {
	workDir := t.TempDir()
	configPath := filepath.Join(workDir, ".codex", "config.toml")
	if err := os.MkdirAll(filepath.Dir(configPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte(`
custom = "keep"
model = "old"

[features]
existing_feature = true

[agents]
existing_limit = 3
`), 0o644); err != nil {
		t.Fatal(err)
	}

	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	var configAction install.Action
	for _, action := range plan.Actions {
		if action.Path == configPath {
			configAction = action
			break
		}
	}
	if configAction.Path == "" {
		t.Fatalf("config action not found")
	}
	if configAction.Kind != install.ActionUpdate {
		t.Fatalf("config action kind = %q", configAction.Kind)
	}

	config := string(configAction.Content)
	for _, want := range []string{
		"custom = 'keep'",
		"model = 'gpt'",
		"existing_feature = true",
		"multi_agent = true",
		"existing_limit = 3",
		"max_threads = 7",
		"max_depth = 2",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("expected config.toml to contain %q, got:\n%s", want, config)
		}
	}
}

func actionContent(t *testing.T, plan install.Plan, path string) string {
	t.Helper()
	for _, action := range plan.Actions {
		if action.Path == path {
			return string(action.Content)
		}
	}
	t.Fatalf("expected action for %s, got %#v", path, plan.Actions)
	return ""
}

func testFlow() ir.Flow {
	return ir.Flow{
		ID:      "test",
		Version: 1,
		ModelSlots: map[string]ir.ModelSlot{
			"main": {},
		},
		PermissionProfiles: map[string]ir.PermissionProfile{
			"read": {
				Capabilities: map[string]string{
					"edit_files": "deny",
				},
			},
		},
		Agents: map[string]ir.Agent{
			"reviewer": {
				ID:                "reviewer",
				Description:       "Reviews",
				ModelSlot:         "main",
				ReasoningEffort:   "medium",
				PermissionProfile: "read",
				Prompt:            "Review.",
			},
		},
		Instructions: map[string]string{"AGENTS.md": "# Test"},
	}
}
