package claude

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cairon666/agentsflow/internal/adapter"
	"github.com/cairon666/agentsflow/internal/binding"
	"github.com/cairon666/agentsflow/internal/install"
	"github.com/cairon666/agentsflow/internal/ir"
)

func TestRenderOmitsGeneratedMarker(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	for _, action := range plan.Actions {
		if strings.Contains(string(action.Content), "Generated by agentsflow") {
			t.Fatalf("action %s contains generated marker:\n%s", action.Path, action.Content)
		}
	}
}

func TestRenderProjectInstructionsInlineCLAUDE(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	claudePath := filepath.Join(workDir, "CLAUDE.md")
	if content := actionContent(t, plan, claudePath); content != "# Test" {
		t.Fatalf("CLAUDE.md = %q, want inline instructions", content)
	}
	settingsPath := filepath.Join(workDir, ".claude", "settings.json")
	settings := actionContent(t, plan, settingsPath)
	for _, want := range []string{
		`"alwaysThinkingEnabled": true`,
		`"model": "gpt"`,
		`"multiAgent": true`,
	} {
		if !strings.Contains(settings, want) {
			t.Fatalf("settings.json missing %q:\n%s", want, settings)
		}
	}
	agent := actionContent(t, plan, filepath.Join(workDir, ".claude", "agents", "reviewer.md"))
	for _, want := range []string{
		"name: reviewer",
		"description: Reviews",
		"model: gpt",
		"effort: medium",
		"Review.",
	} {
		if !strings.Contains(agent, want) {
			t.Fatalf("reviewer.md missing %q:\n%s", want, agent)
		}
	}
	for _, action := range plan.Actions {
		if action.Path == filepath.Join(workDir, "AGENTS.md") {
			t.Fatalf("unexpected AGENTS.md action: %#v", action)
		}
	}
}

func TestRenderClaudeWebToolsFromCapabilities(t *testing.T) {
	workDir := t.TempDir()
	flow := testFlow()
	flow.PermissionProfiles["docs"] = ir.PermissionProfile{
		Capabilities: map[string]string{
			"edit_files": "deny",
			"fetch_urls": "allow",
			"web_search": "allow",
		},
	}
	agent := flow.Agents["reviewer"]
	agent.PermissionProfile = "docs"
	flow.Agents["reviewer"] = agent
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    flow,
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	content := actionContent(t, plan, filepath.Join(workDir, ".claude", "agents", "reviewer.md"))
	for _, want := range []string{"- WebFetch", "- WebSearch"} {
		if !strings.Contains(content, want) {
			t.Fatalf("agent frontmatter missing %q:\n%s", want, content)
		}
	}
}

func TestRenderMergesSettingsJSON(t *testing.T) {
	workDir := t.TempDir()
	settingsPath := filepath.Join(workDir, ".claude", "settings.json")
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(settingsPath, []byte(`{"custom":true,"model":"old"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	var settingsAction install.Action
	for _, action := range plan.Actions {
		if action.Path == settingsPath {
			settingsAction = action
			break
		}
	}
	if settingsAction.Path == "" {
		t.Fatalf("settings action not found")
	}
	if settingsAction.Kind != install.ActionUpdate {
		t.Fatalf("settings action kind = %q", settingsAction.Kind)
	}
	var settings map[string]any
	if err := json.Unmarshal(settingsAction.Content, &settings); err != nil {
		t.Fatal(err)
	}
	if settings["custom"] != true {
		t.Fatalf("custom setting was not preserved: %#v", settings)
	}
	if settings["model"] != "gpt" {
		t.Fatalf("model = %#v", settings["model"])
	}
	if settings["alwaysThinkingEnabled"] != true {
		t.Fatalf("alwaysThinkingEnabled = %#v", settings["alwaysThinkingEnabled"])
	}
	features, ok := settings["features"].(map[string]any)
	if !ok || features["multiAgent"] != true {
		t.Fatalf("features = %#v", settings["features"])
	}
}

func actionContent(t *testing.T, plan install.Plan, path string) string {
	t.Helper()
	for _, action := range plan.Actions {
		if action.Path == path {
			return string(action.Content)
		}
	}
	t.Fatalf("expected action for %s, got %#v", path, plan.Actions)
	return ""
}

func testFlow() ir.Flow {
	return ir.Flow{
		ID:      "test",
		Version: 1,
		ModelSlots: map[string]ir.ModelSlot{
			"main": {},
		},
		PermissionProfiles: map[string]ir.PermissionProfile{
			"read": {
				Capabilities: map[string]string{
					"edit_files": "deny",
				},
			},
		},
		Agents: map[string]ir.Agent{
			"reviewer": {
				ID:                "reviewer",
				Description:       "Reviews",
				ModelSlot:         "main",
				ReasoningEffort:   "medium",
				PermissionProfile: "read",
				Prompt:            "Review.",
			},
		},
		Instructions: map[string]string{"AGENTS.md": "# Test"},
	}
}
