// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package choices

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHistoryReporter creates a new instance of MockHistoryReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryReporter {
	mock := &MockHistoryReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHistoryReporter is an autogenerated mock type for the HistoryReporter type
type MockHistoryReporter struct {
	mock.Mock
}

type MockHistoryReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryReporter) EXPECT() *MockHistoryReporter_Expecter {
	return &MockHistoryReporter_Expecter{mock: &_m.Mock}
}

// HistorySpace provides a mock function for the type MockHistoryReporter
func (_mock *MockHistoryReporter) HistorySpace() {
	_mock.Called()
	return
}

// MockHistoryReporter_HistorySpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistorySpace'
type MockHistoryReporter_HistorySpace_Call struct {
	*mock.Call
}

// HistorySpace is a helper method to define mock.On call
func (_e *MockHistoryReporter_Expecter) HistorySpace() *MockHistoryReporter_HistorySpace_Call {
	return &MockHistoryReporter_HistorySpace_Call{Call: _e.mock.On("HistorySpace")}
}

func (_c *MockHistoryReporter_HistorySpace_Call) Run(run func()) *MockHistoryReporter_HistorySpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHistoryReporter_HistorySpace_Call) Return() *MockHistoryReporter_HistorySpace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHistoryReporter_HistorySpace_Call) RunAndReturn(run func()) *MockHistoryReporter_HistorySpace_Call {
	_c.Run(run)
	return _c
}

// Historyf provides a mock function for the type MockHistoryReporter
func (_mock *MockHistoryReporter) Historyf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockHistoryReporter_Historyf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Historyf'
type MockHistoryReporter_Historyf_Call struct {
	*mock.Call
}

// Historyf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockHistoryReporter_Expecter) Historyf(format interface{}, args ...interface{}) *MockHistoryReporter_Historyf_Call {
	return &MockHistoryReporter_Historyf_Call{Call: _e.mock.On("Historyf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockHistoryReporter_Historyf_Call) Run(run func(format string, args ...any)) *MockHistoryReporter_Historyf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHistoryReporter_Historyf_Call) Return() *MockHistoryReporter_Historyf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHistoryReporter_Historyf_Call) RunAndReturn(run func(format string, args ...any)) *MockHistoryReporter_Historyf_Call {
	_c.Run(run)
	return _c
}
