// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"context"

	"github.com/cairon666/agentsflow/internal/binding"
	"github.com/cairon666/agentsflow/internal/diagnostic"
	"github.com/cairon666/agentsflow/internal/flow"
	"github.com/cairon666/agentsflow/internal/install"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Banner provides a mock function for the type MockReporter
func (_mock *MockReporter) Banner() {
	_mock.Called()
	return
}

// MockReporter_Banner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Banner'
type MockReporter_Banner_Call struct {
	*mock.Call
}

// Banner is a helper method to define mock.On call
func (_e *MockReporter_Expecter) Banner() *MockReporter_Banner_Call {
	return &MockReporter_Banner_Call{Call: _e.mock.On("Banner")}
}

func (_c *MockReporter_Banner_Call) Run(run func()) *MockReporter_Banner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReporter_Banner_Call) Return() *MockReporter_Banner_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Banner_Call) RunAndReturn(run func()) *MockReporter_Banner_Call {
	_c.Run(run)
	return _c
}

// HistoryBlock provides a mock function for the type MockReporter
func (_mock *MockReporter) HistoryBlock(text string) {
	_mock.Called(text)
	return
}

// MockReporter_HistoryBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistoryBlock'
type MockReporter_HistoryBlock_Call struct {
	*mock.Call
}

// HistoryBlock is a helper method to define mock.On call
//   - text string
func (_e *MockReporter_Expecter) HistoryBlock(text interface{}) *MockReporter_HistoryBlock_Call {
	return &MockReporter_HistoryBlock_Call{Call: _e.mock.On("HistoryBlock", text)}
}

func (_c *MockReporter_HistoryBlock_Call) Run(run func(text string)) *MockReporter_HistoryBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporter_HistoryBlock_Call) Return() *MockReporter_HistoryBlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_HistoryBlock_Call) RunAndReturn(run func(text string)) *MockReporter_HistoryBlock_Call {
	_c.Run(run)
	return _c
}

// HistorySpace provides a mock function for the type MockReporter
func (_mock *MockReporter) HistorySpace() {
	_mock.Called()
	return
}

// MockReporter_HistorySpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistorySpace'
type MockReporter_HistorySpace_Call struct {
	*mock.Call
}

// HistorySpace is a helper method to define mock.On call
func (_e *MockReporter_Expecter) HistorySpace() *MockReporter_HistorySpace_Call {
	return &MockReporter_HistorySpace_Call{Call: _e.mock.On("HistorySpace")}
}

func (_c *MockReporter_HistorySpace_Call) Run(run func()) *MockReporter_HistorySpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReporter_HistorySpace_Call) Return() *MockReporter_HistorySpace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_HistorySpace_Call) RunAndReturn(run func()) *MockReporter_HistorySpace_Call {
	_c.Run(run)
	return _c
}

// Historyf provides a mock function for the type MockReporter
func (_mock *MockReporter) Historyf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockReporter_Historyf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Historyf'
type MockReporter_Historyf_Call struct {
	*mock.Call
}

// Historyf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockReporter_Expecter) Historyf(format interface{}, args ...interface{}) *MockReporter_Historyf_Call {
	return &MockReporter_Historyf_Call{Call: _e.mock.On("Historyf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockReporter_Historyf_Call) Run(run func(format string, args ...any)) *MockReporter_Historyf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockReporter_Historyf_Call) Return() *MockReporter_Historyf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Historyf_Call) RunAndReturn(run func(format string, args ...any)) *MockReporter_Historyf_Call {
	_c.Run(run)
	return _c
}

// Message provides a mock function for the type MockReporter
func (_mock *MockReporter) Message(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockReporter_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockReporter_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
//   - args ...any
func (_e *MockReporter_Expecter) Message(args ...interface{}) *MockReporter_Message_Call {
	return &MockReporter_Message_Call{Call: _e.mock.On("Message",
		append([]interface{}{}, args...)...)}
}

func (_c *MockReporter_Message_Call) Run(run func(args ...any)) *MockReporter_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockReporter_Message_Call) Return() *MockReporter_Message_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Message_Call) RunAndReturn(run func(args ...any)) *MockReporter_Message_Call {
	_c.Run(run)
	return _c
}

// MessageLine provides a mock function for the type MockReporter
func (_mock *MockReporter) MessageLine(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockReporter_MessageLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageLine'
type MockReporter_MessageLine_Call struct {
	*mock.Call
}

// MessageLine is a helper method to define mock.On call
//   - args ...any
func (_e *MockReporter_Expecter) MessageLine(args ...interface{}) *MockReporter_MessageLine_Call {
	return &MockReporter_MessageLine_Call{Call: _e.mock.On("MessageLine",
		append([]interface{}{}, args...)...)}
}

func (_c *MockReporter_MessageLine_Call) Run(run func(args ...any)) *MockReporter_MessageLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockReporter_MessageLine_Call) Return() *MockReporter_MessageLine_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_MessageLine_Call) RunAndReturn(run func(args ...any)) *MockReporter_MessageLine_Call {
	_c.Run(run)
	return _c
}

// RunLoading provides a mock function for the type MockReporter
func (_mock *MockReporter) RunLoading(context1 context.Context, s string, fn func(context.Context) error) error {
	ret := _mock.Called(context1, s, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunLoading")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) error); ok {
		r0 = returnFunc(context1, s, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReporter_RunLoading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunLoading'
type MockReporter_RunLoading_Call struct {
	*mock.Call
}

// RunLoading is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - fn func(context.Context) error
func (_e *MockReporter_Expecter) RunLoading(context1 interface{}, s interface{}, fn interface{}) *MockReporter_RunLoading_Call {
	return &MockReporter_RunLoading_Call{Call: _e.mock.On("RunLoading", context1, s, fn)}
}

func (_c *MockReporter_RunLoading_Call) Run(run func(context1 context.Context, s string, fn func(context.Context) error)) *MockReporter_RunLoading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(context.Context) error
		if args[2] != nil {
			arg2 = args[2].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReporter_RunLoading_Call) Return(err error) *MockReporter_RunLoading_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReporter_RunLoading_Call) RunAndReturn(run func(context1 context.Context, s string, fn func(context.Context) error) error) *MockReporter_RunLoading_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateSource creates a new instance of MockTemplateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateSource {
	mock := &MockTemplateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateSource is an autogenerated mock type for the TemplateSource type
type MockTemplateSource struct {
	mock.Mock
}

type MockTemplateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateSource) EXPECT() *MockTemplateSource_Expecter {
	return &MockTemplateSource_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockTemplateSource
func (_mock *MockTemplateSource) Resolve(context1 context.Context, s string, templateChooser TemplateChooser, reporter Reporter) (ResolvedSource, error) {
	ret := _mock.Called(context1, s, templateChooser, reporter)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 ResolvedSource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, TemplateChooser, Reporter) (ResolvedSource, error)); ok {
		return returnFunc(context1, s, templateChooser, reporter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, TemplateChooser, Reporter) ResolvedSource); ok {
		r0 = returnFunc(context1, s, templateChooser, reporter)
	} else {
		r0 = ret.Get(0).(ResolvedSource)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, TemplateChooser, Reporter) error); ok {
		r1 = returnFunc(context1, s, templateChooser, reporter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateSource_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockTemplateSource_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - templateChooser TemplateChooser
//   - reporter Reporter
func (_e *MockTemplateSource_Expecter) Resolve(context1 interface{}, s interface{}, templateChooser interface{}, reporter interface{}) *MockTemplateSource_Resolve_Call {
	return &MockTemplateSource_Resolve_Call{Call: _e.mock.On("Resolve", context1, s, templateChooser, reporter)}
}

func (_c *MockTemplateSource_Resolve_Call) Run(run func(context1 context.Context, s string, templateChooser TemplateChooser, reporter Reporter)) *MockTemplateSource_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 TemplateChooser
		if args[2] != nil {
			arg2 = args[2].(TemplateChooser)
		}
		var arg3 Reporter
		if args[3] != nil {
			arg3 = args[3].(Reporter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTemplateSource_Resolve_Call) Return(resolvedSource ResolvedSource, err error) *MockTemplateSource_Resolve_Call {
	_c.Call.Return(resolvedSource, err)
	return _c
}

func (_c *MockTemplateSource_Resolve_Call) RunAndReturn(run func(context1 context.Context, s string, templateChooser TemplateChooser, reporter Reporter) (ResolvedSource, error)) *MockTemplateSource_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlowLoader creates a new instance of MockFlowLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowLoader {
	mock := &MockFlowLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlowLoader is an autogenerated mock type for the FlowLoader type
type MockFlowLoader struct {
	mock.Mock
}

type MockFlowLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlowLoader) EXPECT() *MockFlowLoader_Expecter {
	return &MockFlowLoader_Expecter{mock: &_m.Mock}
}

// LoadFile provides a mock function for the type MockFlowLoader
func (_mock *MockFlowLoader) LoadFile(path string) (LoadResult, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadFile")
	}

	var r0 LoadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (LoadResult, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) LoadResult); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(LoadResult)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowLoader_LoadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFile'
type MockFlowLoader_LoadFile_Call struct {
	*mock.Call
}

// LoadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFlowLoader_Expecter) LoadFile(path interface{}) *MockFlowLoader_LoadFile_Call {
	return &MockFlowLoader_LoadFile_Call{Call: _e.mock.On("LoadFile", path)}
}

func (_c *MockFlowLoader_LoadFile_Call) Run(run func(path string)) *MockFlowLoader_LoadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowLoader_LoadFile_Call) Return(loadResult LoadResult, err error) *MockFlowLoader_LoadFile_Call {
	_c.Call.Return(loadResult, err)
	return _c
}

func (_c *MockFlowLoader_LoadFile_Call) RunAndReturn(run func(path string) (LoadResult, error)) *MockFlowLoader_LoadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChoiceCollector creates a new instance of MockChoiceCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChoiceCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChoiceCollector {
	mock := &MockChoiceCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChoiceCollector is an autogenerated mock type for the ChoiceCollector type
type MockChoiceCollector struct {
	mock.Mock
}

type MockChoiceCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChoiceCollector) EXPECT() *MockChoiceCollector_Expecter {
	return &MockChoiceCollector_Expecter{mock: &_m.Mock}
}

// ChooseTemplate provides a mock function for the type MockChoiceCollector
func (_mock *MockChoiceCollector) ChooseTemplate(templateOptions []TemplateOption) (string, error) {
	ret := _mock.Called(templateOptions)

	if len(ret) == 0 {
		panic("no return value specified for ChooseTemplate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]TemplateOption) (string, error)); ok {
		return returnFunc(templateOptions)
	}
	if returnFunc, ok := ret.Get(0).(func([]TemplateOption) string); ok {
		r0 = returnFunc(templateOptions)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]TemplateOption) error); ok {
		r1 = returnFunc(templateOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChoiceCollector_ChooseTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChooseTemplate'
type MockChoiceCollector_ChooseTemplate_Call struct {
	*mock.Call
}

// ChooseTemplate is a helper method to define mock.On call
//   - templateOptions []TemplateOption
func (_e *MockChoiceCollector_Expecter) ChooseTemplate(templateOptions interface{}) *MockChoiceCollector_ChooseTemplate_Call {
	return &MockChoiceCollector_ChooseTemplate_Call{Call: _e.mock.On("ChooseTemplate", templateOptions)}
}

func (_c *MockChoiceCollector_ChooseTemplate_Call) Run(run func(templateOptions []TemplateOption)) *MockChoiceCollector_ChooseTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []TemplateOption
		if args[0] != nil {
			arg0 = args[0].([]TemplateOption)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChoiceCollector_ChooseTemplate_Call) Return(s string, err error) *MockChoiceCollector_ChooseTemplate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChoiceCollector_ChooseTemplate_Call) RunAndReturn(run func(templateOptions []TemplateOption) (string, error)) *MockChoiceCollector_ChooseTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// Collect provides a mock function for the type MockChoiceCollector
func (_mock *MockChoiceCollector) Collect(context1 context.Context, flow1 flow.Flow, targetOptions []TargetOption) (Choices, error) {
	ret := _mock.Called(context1, flow1, targetOptions)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 Choices
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flow.Flow, []TargetOption) (Choices, error)); ok {
		return returnFunc(context1, flow1, targetOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, flow.Flow, []TargetOption) Choices); ok {
		r0 = returnFunc(context1, flow1, targetOptions)
	} else {
		r0 = ret.Get(0).(Choices)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, flow.Flow, []TargetOption) error); ok {
		r1 = returnFunc(context1, flow1, targetOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChoiceCollector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type MockChoiceCollector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - context1 context.Context
//   - flow1 flow.Flow
//   - targetOptions []TargetOption
func (_e *MockChoiceCollector_Expecter) Collect(context1 interface{}, flow1 interface{}, targetOptions interface{}) *MockChoiceCollector_Collect_Call {
	return &MockChoiceCollector_Collect_Call{Call: _e.mock.On("Collect", context1, flow1, targetOptions)}
}

func (_c *MockChoiceCollector_Collect_Call) Run(run func(context1 context.Context, flow1 flow.Flow, targetOptions []TargetOption)) *MockChoiceCollector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flow.Flow
		if args[1] != nil {
			arg1 = args[1].(flow.Flow)
		}
		var arg2 []TargetOption
		if args[2] != nil {
			arg2 = args[2].([]TargetOption)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChoiceCollector_Collect_Call) Return(choices Choices, err error) *MockChoiceCollector_Collect_Call {
	_c.Call.Return(choices, err)
	return _c
}

func (_c *MockChoiceCollector_Collect_Call) RunAndReturn(run func(context1 context.Context, flow1 flow.Flow, targetOptions []TargetOption) (Choices, error)) *MockChoiceCollector_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type MockChoiceCollector
func (_mock *MockChoiceCollector) Confirm(context1 context.Context, s string) (bool, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChoiceCollector_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockChoiceCollector_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockChoiceCollector_Expecter) Confirm(context1 interface{}, s interface{}) *MockChoiceCollector_Confirm_Call {
	return &MockChoiceCollector_Confirm_Call{Call: _e.mock.On("Confirm", context1, s)}
}

func (_c *MockChoiceCollector_Confirm_Call) Run(run func(context1 context.Context, s string)) *MockChoiceCollector_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChoiceCollector_Confirm_Call) Return(b bool, err error) *MockChoiceCollector_Confirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChoiceCollector_Confirm_Call) RunAndReturn(run func(context1 context.Context, s string) (bool, error)) *MockChoiceCollector_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetRenderer creates a new instance of MockTargetRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetRenderer {
	mock := &MockTargetRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTargetRenderer is an autogenerated mock type for the TargetRenderer type
type MockTargetRenderer struct {
	mock.Mock
}

type MockTargetRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetRenderer) EXPECT() *MockTargetRenderer_Expecter {
	return &MockTargetRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockTargetRenderer
func (_mock *MockTargetRenderer) Render(context1 context.Context, renderInput RenderInput) (install.ArtifactSet, []diagnostic.Diagnostic) {
	ret := _mock.Called(context1, renderInput)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 install.ArtifactSet
	var r1 []diagnostic.Diagnostic
	if returnFunc, ok := ret.Get(0).(func(context.Context, RenderInput) (install.ArtifactSet, []diagnostic.Diagnostic)); ok {
		return returnFunc(context1, renderInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, RenderInput) install.ArtifactSet); ok {
		r0 = returnFunc(context1, renderInput)
	} else {
		r0 = ret.Get(0).(install.ArtifactSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, RenderInput) []diagnostic.Diagnostic); ok {
		r1 = returnFunc(context1, renderInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]diagnostic.Diagnostic)
		}
	}
	return r0, r1
}

// MockTargetRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockTargetRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - context1 context.Context
//   - renderInput RenderInput
func (_e *MockTargetRenderer_Expecter) Render(context1 interface{}, renderInput interface{}) *MockTargetRenderer_Render_Call {
	return &MockTargetRenderer_Render_Call{Call: _e.mock.On("Render", context1, renderInput)}
}

func (_c *MockTargetRenderer_Render_Call) Run(run func(context1 context.Context, renderInput RenderInput)) *MockTargetRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RenderInput
		if args[1] != nil {
			arg1 = args[1].(RenderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetRenderer_Render_Call) Return(artifactSet install.ArtifactSet, diagnostics []diagnostic.Diagnostic) *MockTargetRenderer_Render_Call {
	_c.Call.Return(artifactSet, diagnostics)
	return _c
}

func (_c *MockTargetRenderer_Render_Call) RunAndReturn(run func(context1 context.Context, renderInput RenderInput) (install.ArtifactSet, []diagnostic.Diagnostic)) *MockTargetRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// Target provides a mock function for the type MockTargetRenderer
func (_mock *MockTargetRenderer) Target() binding.Target {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Target")
	}

	var r0 binding.Target
	if returnFunc, ok := ret.Get(0).(func() binding.Target); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(binding.Target)
	}
	return r0
}

// MockTargetRenderer_Target_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Target'
type MockTargetRenderer_Target_Call struct {
	*mock.Call
}

// Target is a helper method to define mock.On call
func (_e *MockTargetRenderer_Expecter) Target() *MockTargetRenderer_Target_Call {
	return &MockTargetRenderer_Target_Call{Call: _e.mock.On("Target")}
}

func (_c *MockTargetRenderer_Target_Call) Run(run func()) *MockTargetRenderer_Target_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTargetRenderer_Target_Call) Return(target binding.Target) *MockTargetRenderer_Target_Call {
	_c.Call.Return(target)
	return _c
}

func (_c *MockTargetRenderer_Target_Call) RunAndReturn(run func() binding.Target) *MockTargetRenderer_Target_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockTargetRenderer
func (_mock *MockTargetRenderer) Validate(context1 context.Context, renderInput RenderInput) []diagnostic.Diagnostic {
	ret := _mock.Called(context1, renderInput)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []diagnostic.Diagnostic
	if returnFunc, ok := ret.Get(0).(func(context.Context, RenderInput) []diagnostic.Diagnostic); ok {
		r0 = returnFunc(context1, renderInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]diagnostic.Diagnostic)
		}
	}
	return r0
}

// MockTargetRenderer_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTargetRenderer_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - context1 context.Context
//   - renderInput RenderInput
func (_e *MockTargetRenderer_Expecter) Validate(context1 interface{}, renderInput interface{}) *MockTargetRenderer_Validate_Call {
	return &MockTargetRenderer_Validate_Call{Call: _e.mock.On("Validate", context1, renderInput)}
}

func (_c *MockTargetRenderer_Validate_Call) Run(run func(context1 context.Context, renderInput RenderInput)) *MockTargetRenderer_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RenderInput
		if args[1] != nil {
			arg1 = args[1].(RenderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetRenderer_Validate_Call) Return(diagnostics []diagnostic.Diagnostic) *MockTargetRenderer_Validate_Call {
	_c.Call.Return(diagnostics)
	return _c
}

func (_c *MockTargetRenderer_Validate_Call) RunAndReturn(run func(context1 context.Context, renderInput RenderInput) []diagnostic.Diagnostic) *MockTargetRenderer_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetRegistry creates a new instance of MockTargetRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetRegistry {
	mock := &MockTargetRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTargetRegistry is an autogenerated mock type for the TargetRegistry type
type MockTargetRegistry struct {
	mock.Mock
}

type MockTargetRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetRegistry) EXPECT() *MockTargetRegistry_Expecter {
	return &MockTargetRegistry_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockTargetRegistry
func (_mock *MockTargetRegistry) All() []TargetRenderer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []TargetRenderer
	if returnFunc, ok := ret.Get(0).(func() []TargetRenderer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TargetRenderer)
		}
	}
	return r0
}

// MockTargetRegistry_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockTargetRegistry_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockTargetRegistry_Expecter) All() *MockTargetRegistry_All_Call {
	return &MockTargetRegistry_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockTargetRegistry_All_Call) Run(run func()) *MockTargetRegistry_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTargetRegistry_All_Call) Return(targetRenderers []TargetRenderer) *MockTargetRegistry_All_Call {
	_c.Call.Return(targetRenderers)
	return _c
}

func (_c *MockTargetRegistry_All_Call) RunAndReturn(run func() []TargetRenderer) *MockTargetRegistry_All_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTargetRegistry
func (_mock *MockTargetRegistry) Get(s string) (TargetRenderer, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 TargetRenderer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (TargetRenderer, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) TargetRenderer); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TargetRenderer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTargetRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockTargetRegistry_Expecter) Get(s interface{}) *MockTargetRegistry_Get_Call {
	return &MockTargetRegistry_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockTargetRegistry_Get_Call) Run(run func(s string)) *MockTargetRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTargetRegistry_Get_Call) Return(targetRenderer TargetRenderer, err error) *MockTargetRegistry_Get_Call {
	_c.Call.Return(targetRenderer, err)
	return _c
}

func (_c *MockTargetRegistry_Get_Call) RunAndReturn(run func(s string) (TargetRenderer, error)) *MockTargetRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockTargetRegistry
func (_mock *MockTargetRegistry) Resolve(s string) (binding.Target, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 binding.Target
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (binding.Target, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) binding.Target); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(binding.Target)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetRegistry_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockTargetRegistry_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - s string
func (_e *MockTargetRegistry_Expecter) Resolve(s interface{}) *MockTargetRegistry_Resolve_Call {
	return &MockTargetRegistry_Resolve_Call{Call: _e.mock.On("Resolve", s)}
}

func (_c *MockTargetRegistry_Resolve_Call) Run(run func(s string)) *MockTargetRegistry_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTargetRegistry_Resolve_Call) Return(target binding.Target, err error) *MockTargetRegistry_Resolve_Call {
	_c.Call.Return(target, err)
	return _c
}

func (_c *MockTargetRegistry_Resolve_Call) RunAndReturn(run func(s string) (binding.Target, error)) *MockTargetRegistry_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExportChoiceCollector creates a new instance of MockExportChoiceCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExportChoiceCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExportChoiceCollector {
	mock := &MockExportChoiceCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExportChoiceCollector is an autogenerated mock type for the ExportChoiceCollector type
type MockExportChoiceCollector struct {
	mock.Mock
}

type MockExportChoiceCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExportChoiceCollector) EXPECT() *MockExportChoiceCollector_Expecter {
	return &MockExportChoiceCollector_Expecter{mock: &_m.Mock}
}

// CollectExport provides a mock function for the type MockExportChoiceCollector
func (_mock *MockExportChoiceCollector) CollectExport(context1 context.Context, exportSourceOptions []ExportSourceOption) (ExportChoices, error) {
	ret := _mock.Called(context1, exportSourceOptions)

	if len(ret) == 0 {
		panic("no return value specified for CollectExport")
	}

	var r0 ExportChoices
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ExportSourceOption) (ExportChoices, error)); ok {
		return returnFunc(context1, exportSourceOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ExportSourceOption) ExportChoices); ok {
		r0 = returnFunc(context1, exportSourceOptions)
	} else {
		r0 = ret.Get(0).(ExportChoices)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []ExportSourceOption) error); ok {
		r1 = returnFunc(context1, exportSourceOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExportChoiceCollector_CollectExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectExport'
type MockExportChoiceCollector_CollectExport_Call struct {
	*mock.Call
}

// CollectExport is a helper method to define mock.On call
//   - context1 context.Context
//   - exportSourceOptions []ExportSourceOption
func (_e *MockExportChoiceCollector_Expecter) CollectExport(context1 interface{}, exportSourceOptions interface{}) *MockExportChoiceCollector_CollectExport_Call {
	return &MockExportChoiceCollector_CollectExport_Call{Call: _e.mock.On("CollectExport", context1, exportSourceOptions)}
}

func (_c *MockExportChoiceCollector_CollectExport_Call) Run(run func(context1 context.Context, exportSourceOptions []ExportSourceOption)) *MockExportChoiceCollector_CollectExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ExportSourceOption
		if args[1] != nil {
			arg1 = args[1].([]ExportSourceOption)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExportChoiceCollector_CollectExport_Call) Return(exportChoices ExportChoices, err error) *MockExportChoiceCollector_CollectExport_Call {
	_c.Call.Return(exportChoices, err)
	return _c
}

func (_c *MockExportChoiceCollector_CollectExport_Call) RunAndReturn(run func(context1 context.Context, exportSourceOptions []ExportSourceOption) (ExportChoices, error)) *MockExportChoiceCollector_CollectExport_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type MockExportChoiceCollector
func (_mock *MockExportChoiceCollector) Confirm(context1 context.Context, s string) (bool, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExportChoiceCollector_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockExportChoiceCollector_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockExportChoiceCollector_Expecter) Confirm(context1 interface{}, s interface{}) *MockExportChoiceCollector_Confirm_Call {
	return &MockExportChoiceCollector_Confirm_Call{Call: _e.mock.On("Confirm", context1, s)}
}

func (_c *MockExportChoiceCollector_Confirm_Call) Run(run func(context1 context.Context, s string)) *MockExportChoiceCollector_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExportChoiceCollector_Confirm_Call) Return(b bool, err error) *MockExportChoiceCollector_Confirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockExportChoiceCollector_Confirm_Call) RunAndReturn(run func(context1 context.Context, s string) (bool, error)) *MockExportChoiceCollector_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourceExporter creates a new instance of MockSourceExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceExporter {
	mock := &MockSourceExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSourceExporter is an autogenerated mock type for the SourceExporter type
type MockSourceExporter struct {
	mock.Mock
}

type MockSourceExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceExporter) EXPECT() *MockSourceExporter_Expecter {
	return &MockSourceExporter_Expecter{mock: &_m.Mock}
}

// Export provides a mock function for the type MockSourceExporter
func (_mock *MockSourceExporter) Export(context1 context.Context, exportInput ExportInput) (ExportResult, error) {
	ret := _mock.Called(context1, exportInput)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 ExportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExportInput) (ExportResult, error)); ok {
		return returnFunc(context1, exportInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExportInput) ExportResult); ok {
		r0 = returnFunc(context1, exportInput)
	} else {
		r0 = ret.Get(0).(ExportResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ExportInput) error); ok {
		r1 = returnFunc(context1, exportInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceExporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockSourceExporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - context1 context.Context
//   - exportInput ExportInput
func (_e *MockSourceExporter_Expecter) Export(context1 interface{}, exportInput interface{}) *MockSourceExporter_Export_Call {
	return &MockSourceExporter_Export_Call{Call: _e.mock.On("Export", context1, exportInput)}
}

func (_c *MockSourceExporter_Export_Call) Run(run func(context1 context.Context, exportInput ExportInput)) *MockSourceExporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ExportInput
		if args[1] != nil {
			arg1 = args[1].(ExportInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceExporter_Export_Call) Return(exportResult ExportResult, err error) *MockSourceExporter_Export_Call {
	_c.Call.Return(exportResult, err)
	return _c
}

func (_c *MockSourceExporter_Export_Call) RunAndReturn(run func(context1 context.Context, exportInput ExportInput) (ExportResult, error)) *MockSourceExporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// Source provides a mock function for the type MockSourceExporter
func (_mock *MockSourceExporter) Source() binding.Target {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Source")
	}

	var r0 binding.Target
	if returnFunc, ok := ret.Get(0).(func() binding.Target); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(binding.Target)
	}
	return r0
}

// MockSourceExporter_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type MockSourceExporter_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *MockSourceExporter_Expecter) Source() *MockSourceExporter_Source_Call {
	return &MockSourceExporter_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *MockSourceExporter_Source_Call) Run(run func()) *MockSourceExporter_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSourceExporter_Source_Call) Return(target binding.Target) *MockSourceExporter_Source_Call {
	_c.Call.Return(target)
	return _c
}

func (_c *MockSourceExporter_Source_Call) RunAndReturn(run func() binding.Target) *MockSourceExporter_Source_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExporterRegistry creates a new instance of MockExporterRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExporterRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExporterRegistry {
	mock := &MockExporterRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExporterRegistry is an autogenerated mock type for the ExporterRegistry type
type MockExporterRegistry struct {
	mock.Mock
}

type MockExporterRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExporterRegistry) EXPECT() *MockExporterRegistry_Expecter {
	return &MockExporterRegistry_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockExporterRegistry
func (_mock *MockExporterRegistry) All() []SourceExporter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []SourceExporter
	if returnFunc, ok := ret.Get(0).(func() []SourceExporter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SourceExporter)
		}
	}
	return r0
}

// MockExporterRegistry_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockExporterRegistry_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockExporterRegistry_Expecter) All() *MockExporterRegistry_All_Call {
	return &MockExporterRegistry_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockExporterRegistry_All_Call) Run(run func()) *MockExporterRegistry_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExporterRegistry_All_Call) Return(sourceExporters []SourceExporter) *MockExporterRegistry_All_Call {
	_c.Call.Return(sourceExporters)
	return _c
}

func (_c *MockExporterRegistry_All_Call) RunAndReturn(run func() []SourceExporter) *MockExporterRegistry_All_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockExporterRegistry
func (_mock *MockExporterRegistry) Get(s string) (SourceExporter, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 SourceExporter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (SourceExporter, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) SourceExporter); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SourceExporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExporterRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExporterRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockExporterRegistry_Expecter) Get(s interface{}) *MockExporterRegistry_Get_Call {
	return &MockExporterRegistry_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockExporterRegistry_Get_Call) Run(run func(s string)) *MockExporterRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExporterRegistry_Get_Call) Return(sourceExporter SourceExporter, err error) *MockExporterRegistry_Get_Call {
	_c.Call.Return(sourceExporter, err)
	return _c
}

func (_c *MockExporterRegistry_Get_Call) RunAndReturn(run func(s string) (SourceExporter, error)) *MockExporterRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockExporterRegistry
func (_mock *MockExporterRegistry) Resolve(s string) (binding.Target, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 binding.Target
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (binding.Target, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) binding.Target); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(binding.Target)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExporterRegistry_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockExporterRegistry_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - s string
func (_e *MockExporterRegistry_Expecter) Resolve(s interface{}) *MockExporterRegistry_Resolve_Call {
	return &MockExporterRegistry_Resolve_Call{Call: _e.mock.On("Resolve", s)}
}

func (_c *MockExporterRegistry_Resolve_Call) Run(run func(s string)) *MockExporterRegistry_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExporterRegistry_Resolve_Call) Return(target binding.Target, err error) *MockExporterRegistry_Resolve_Call {
	_c.Call.Return(target, err)
	return _c
}

func (_c *MockExporterRegistry_Resolve_Call) RunAndReturn(run func(s string) (binding.Target, error)) *MockExporterRegistry_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpecEncoder creates a new instance of MockSpecEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecEncoder {
	mock := &MockSpecEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpecEncoder is an autogenerated mock type for the SpecEncoder type
type MockSpecEncoder struct {
	mock.Mock
}

type MockSpecEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecEncoder) EXPECT() *MockSpecEncoder_Expecter {
	return &MockSpecEncoder_Expecter{mock: &_m.Mock}
}

// EncodeSpec provides a mock function for the type MockSpecEncoder
func (_mock *MockSpecEncoder) EncodeSpec(spec flow.Spec) ([]byte, error) {
	ret := _mock.Called(spec)

	if len(ret) == 0 {
		panic("no return value specified for EncodeSpec")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(flow.Spec) ([]byte, error)); ok {
		return returnFunc(spec)
	}
	if returnFunc, ok := ret.Get(0).(func(flow.Spec) []byte); ok {
		r0 = returnFunc(spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(flow.Spec) error); ok {
		r1 = returnFunc(spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecEncoder_EncodeSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeSpec'
type MockSpecEncoder_EncodeSpec_Call struct {
	*mock.Call
}

// EncodeSpec is a helper method to define mock.On call
//   - spec flow.Spec
func (_e *MockSpecEncoder_Expecter) EncodeSpec(spec interface{}) *MockSpecEncoder_EncodeSpec_Call {
	return &MockSpecEncoder_EncodeSpec_Call{Call: _e.mock.On("EncodeSpec", spec)}
}

func (_c *MockSpecEncoder_EncodeSpec_Call) Run(run func(spec flow.Spec)) *MockSpecEncoder_EncodeSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Spec
		if args[0] != nil {
			arg0 = args[0].(flow.Spec)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpecEncoder_EncodeSpec_Call) Return(bytes []byte, err error) *MockSpecEncoder_EncodeSpec_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSpecEncoder_EncodeSpec_Call) RunAndReturn(run func(spec flow.Spec) ([]byte, error)) *MockSpecEncoder_EncodeSpec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstallPlanner creates a new instance of MockInstallPlanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallPlanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallPlanner {
	mock := &MockInstallPlanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallPlanner is an autogenerated mock type for the InstallPlanner type
type MockInstallPlanner struct {
	mock.Mock
}

type MockInstallPlanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallPlanner) EXPECT() *MockInstallPlanner_Expecter {
	return &MockInstallPlanner_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockInstallPlanner
func (_mock *MockInstallPlanner) Build(artifactSet install.ArtifactSet) install.Plan {
	ret := _mock.Called(artifactSet)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 install.Plan
	if returnFunc, ok := ret.Get(0).(func(install.ArtifactSet) install.Plan); ok {
		r0 = returnFunc(artifactSet)
	} else {
		r0 = ret.Get(0).(install.Plan)
	}
	return r0
}

// MockInstallPlanner_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockInstallPlanner_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - artifactSet install.ArtifactSet
func (_e *MockInstallPlanner_Expecter) Build(artifactSet interface{}) *MockInstallPlanner_Build_Call {
	return &MockInstallPlanner_Build_Call{Call: _e.mock.On("Build", artifactSet)}
}

func (_c *MockInstallPlanner_Build_Call) Run(run func(artifactSet install.ArtifactSet)) *MockInstallPlanner_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 install.ArtifactSet
		if args[0] != nil {
			arg0 = args[0].(install.ArtifactSet)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallPlanner_Build_Call) Return(plan install.Plan) *MockInstallPlanner_Build_Call {
	_c.Call.Return(plan)
	return _c
}

func (_c *MockInstallPlanner_Build_Call) RunAndReturn(run func(artifactSet install.ArtifactSet) install.Plan) *MockInstallPlanner_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstallWriter creates a new instance of MockInstallWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallWriter {
	mock := &MockInstallWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallWriter is an autogenerated mock type for the InstallWriter type
type MockInstallWriter struct {
	mock.Mock
}

type MockInstallWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallWriter) EXPECT() *MockInstallWriter_Expecter {
	return &MockInstallWriter_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockInstallWriter
func (_mock *MockInstallWriter) Apply(plan install.Plan) error {
	ret := _mock.Called(plan)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(install.Plan) error); ok {
		r0 = returnFunc(plan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallWriter_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockInstallWriter_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - plan install.Plan
func (_e *MockInstallWriter_Expecter) Apply(plan interface{}) *MockInstallWriter_Apply_Call {
	return &MockInstallWriter_Apply_Call{Call: _e.mock.On("Apply", plan)}
}

func (_c *MockInstallWriter_Apply_Call) Run(run func(plan install.Plan)) *MockInstallWriter_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 install.Plan
		if args[0] != nil {
			arg0 = args[0].(install.Plan)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallWriter_Apply_Call) Return(err error) *MockInstallWriter_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallWriter_Apply_Call) RunAndReturn(run func(plan install.Plan) error) *MockInstallWriter_Apply_Call {
	_c.Call.Return(run)
	return _c
}
