// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package source

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCloner creates a new instance of MockCloner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloner {
	mock := &MockCloner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloner is an autogenerated mock type for the Cloner type
type MockCloner struct {
	mock.Mock
}

type MockCloner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloner) EXPECT() *MockCloner_Expecter {
	return &MockCloner_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function for the type MockCloner
func (_mock *MockCloner) Clone(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCloner_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockCloner_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockCloner_Expecter) Clone(context1 interface{}, s interface{}, s1 interface{}) *MockCloner_Clone_Call {
	return &MockCloner_Clone_Call{Call: _e.mock.On("Clone", context1, s, s1)}
}

func (_c *MockCloner_Clone_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockCloner_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCloner_Clone_Call) Return(err error) *MockCloner_Clone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCloner_Clone_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *MockCloner_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// HistorySpace provides a mock function for the type MockReporter
func (_mock *MockReporter) HistorySpace() {
	_mock.Called()
	return
}

// MockReporter_HistorySpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistorySpace'
type MockReporter_HistorySpace_Call struct {
	*mock.Call
}

// HistorySpace is a helper method to define mock.On call
func (_e *MockReporter_Expecter) HistorySpace() *MockReporter_HistorySpace_Call {
	return &MockReporter_HistorySpace_Call{Call: _e.mock.On("HistorySpace")}
}

func (_c *MockReporter_HistorySpace_Call) Run(run func()) *MockReporter_HistorySpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReporter_HistorySpace_Call) Return() *MockReporter_HistorySpace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_HistorySpace_Call) RunAndReturn(run func()) *MockReporter_HistorySpace_Call {
	_c.Run(run)
	return _c
}

// Historyf provides a mock function for the type MockReporter
func (_mock *MockReporter) Historyf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockReporter_Historyf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Historyf'
type MockReporter_Historyf_Call struct {
	*mock.Call
}

// Historyf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockReporter_Expecter) Historyf(format interface{}, args ...interface{}) *MockReporter_Historyf_Call {
	return &MockReporter_Historyf_Call{Call: _e.mock.On("Historyf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockReporter_Historyf_Call) Run(run func(format string, args ...any)) *MockReporter_Historyf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockReporter_Historyf_Call) Return() *MockReporter_Historyf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Historyf_Call) RunAndReturn(run func(format string, args ...any)) *MockReporter_Historyf_Call {
	_c.Run(run)
	return _c
}

// RunLoading provides a mock function for the type MockReporter
func (_mock *MockReporter) RunLoading(context1 context.Context, s string, fn func(context.Context) error) error {
	ret := _mock.Called(context1, s, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunLoading")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) error); ok {
		r0 = returnFunc(context1, s, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReporter_RunLoading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunLoading'
type MockReporter_RunLoading_Call struct {
	*mock.Call
}

// RunLoading is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - fn func(context.Context) error
func (_e *MockReporter_Expecter) RunLoading(context1 interface{}, s interface{}, fn interface{}) *MockReporter_RunLoading_Call {
	return &MockReporter_RunLoading_Call{Call: _e.mock.On("RunLoading", context1, s, fn)}
}

func (_c *MockReporter_RunLoading_Call) Run(run func(context1 context.Context, s string, fn func(context.Context) error)) *MockReporter_RunLoading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(context.Context) error
		if args[2] != nil {
			arg2 = args[2].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReporter_RunLoading_Call) Return(err error) *MockReporter_RunLoading_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReporter_RunLoading_Call) RunAndReturn(run func(context1 context.Context, s string, fn func(context.Context) error) error) *MockReporter_RunLoading_Call {
	_c.Call.Return(run)
	return _c
}
