package opencode

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cairon666/agentsflow/internal/adapter"
	"github.com/cairon666/agentsflow/internal/binding"
	"github.com/cairon666/agentsflow/internal/install"
	"github.com/cairon666/agentsflow/internal/ir"
)

func TestRenderOmitsGeneratedMarker(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	for _, action := range plan.Actions {
		if strings.Contains(string(action.Content), "Generated by agentsflow") {
			t.Fatalf("action %s contains generated marker:\n%s", action.Path, action.Content)
		}
	}
}

func TestRenderCreatesProjectArtifacts(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	if agents := actionContent(t, plan, filepath.Join(workDir, "AGENTS.md")); agents != "# Test" {
		t.Fatalf("AGENTS.md = %q, want project instructions", agents)
	}

	config := actionContent(t, plan, filepath.Join(workDir, "opencode.json"))
	if !strings.Contains(config, `"model": "gpt"`) {
		t.Fatalf("opencode.json missing model:\n%s", config)
	}

	agent := actionContent(t, plan, filepath.Join(workDir, ".opencode", "agents", "reviewer.md"))
	for _, want := range []string{
		"description: Reviews",
		"mode: subagent",
		"model: gpt",
		"reasoningEffort: medium",
		"edit: deny",
		"Review.",
	} {
		if !strings.Contains(agent, want) {
			t.Fatalf("reviewer.md missing %q:\n%s", want, agent)
		}
	}
}

func actionContent(t *testing.T, plan install.Plan, path string) string {
	t.Helper()
	for _, action := range plan.Actions {
		if action.Path == path {
			return string(action.Content)
		}
	}
	t.Fatalf("expected action for %s, got %#v", path, plan.Actions)
	return ""
}

func testFlow() ir.Flow {
	return ir.Flow{
		ID:      "test",
		Version: 1,
		ModelSlots: map[string]ir.ModelSlot{
			"main": {},
		},
		PermissionProfiles: map[string]ir.PermissionProfile{
			"read": {
				Capabilities: map[string]string{
					"edit_files": "deny",
				},
			},
		},
		Agents: map[string]ir.Agent{
			"reviewer": {
				ID:                "reviewer",
				Description:       "Reviews",
				ModelSlot:         "main",
				ReasoningEffort:   "medium",
				PermissionProfile: "read",
				Prompt:            "Review.",
			},
		},
		Instructions: map[string]string{"AGENTS.md": "# Test"},
	}
}
