package opencode

import (
	"context"
	"strings"
	"testing"

	"github.com/cairon666/agentsflow/internal/adapter"
	"github.com/cairon666/agentsflow/internal/binding"
	"github.com/cairon666/agentsflow/internal/ir"
)

func TestRenderOmitsGeneratedMarker(t *testing.T) {
	workDir := t.TempDir()
	plan, diags := (Adapter{}).Render(context.Background(), adapter.RenderInput{
		Flow:    testFlow(),
		Models:  binding.Models{"main": "gpt"},
		Scope:   binding.ScopeProject,
		WorkDir: workDir,
		HomeDir: t.TempDir(),
	})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	for _, action := range plan.Actions {
		if strings.Contains(string(action.Content), "Generated by agentsflow") {
			t.Fatalf("action %s contains generated marker:\n%s", action.Path, action.Content)
		}
	}
}

func testFlow() ir.Flow {
	return ir.Flow{
		ID:      "test",
		Version: 1,
		ModelSlots: map[string]ir.ModelSlot{
			"main": {},
		},
		PermissionProfiles: map[string]ir.PermissionProfile{
			"read": {
				Capabilities: map[string]string{
					"edit_files": "deny",
				},
			},
		},
		Agents: map[string]ir.Agent{
			"reviewer": {
				ID:                "reviewer",
				Description:       "Reviews",
				ModelSlot:         "main",
				ReasoningEffort:   "medium",
				PermissionProfile: "read",
				Prompt:            "Review.",
			},
		},
		Instructions: map[string]string{"AGENTS.md": "# Test"},
	}
}
